# mysql5.6:
#   image: mysql:5.6
#   container_name: mysql5.6
#   ports:
#     - 3355:3306
#   environment:
#     - MYSQL_DATABASE=flexdq
#     - MYSQL_USER=worker
#     - MYSQL_PASSWORD=worker
#     - MYSQL_ROOT_PASSWORD=root12
#     - TZ=UTC
#   volumes:
#      - ./confs/mysql5.6/conf.d:/etc/mysql/conf.d
#mysql5.5:
#  image: mysql:5.5
#  container_name: docker-mysql-local
#  ports:
#    - 3355:3306
#  environment:
#    - MYSQL_DATABASE=swopydb
#    - MYSQL_USER=worker
#    - MYSQL_PASSWORD=worker
#    - MYSQL_ROOT_PASSWORD=root12
#    - TZ=UTC
#  volumes:
#    - ./confs/mysql5.5/conf.d:/etc/mysql/conf.d


# mysql5.7:
#   image: mysql:5.7
#   container_name: mysql5.7
#   ports:
#     - 3357:3306
#   environment:
#     - MYSQL_DATABASE=work
#     - MYSQL_USER=worker
#     - MYSQL_PASSWORD=worker
#     - MYSQL_ROOT_PASSWORD=root12
#     - TZ=UTC
#   volumes:
#     - ./confs/mysql5.7/conf.d:/etc/mysql/conf.d
mysql8.0:
 image: mysql:8.0
 container_name: mysql8.0
 ports:
   - 3380:3306
 entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
 environment:
   - MYSQL_DATABASE=swopydb
   - MYSQL_USER=worker
   - MYSQL_PASSWORD=worker
   - MYSQL_ROOT_PASSWORD=root12
   - TZ=UTC
 volumes:
   - ./confs/mysql8.0/conf.d:/etc/mysql/conf.d
